language: rust
sudo: required
os: linux

cache: cargo

addons:
  apt:
    packages:
      - zlib1g-dev
      - libcurl4-openssl-dev
      - libiberty-dev
      - libdw-dev
      - binutils-dev

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta
    - os: windows
  fast_finish: true
  include:
    - os: osx
      sudo: required
    - os: windows
      sudo: required

before_install:
  - rustup self update
  - rustup install stable
  - rustup component add rustfmt-preview --toolchain stable

before_script:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then source ./ci/set_path.sh; fi
  - cargo install cargo-update || echo "cargo-update already installed"
  - cargo install cargo-travis || echo "cargo-travis already installed"
  - cargo install-update -a

script:
  - cargo +stable fmt --all -- --check
  - cargo build && cargo test

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo coverage --exclude-pattern '/toshi/src/bin,/src/bin,/bin,/target,/toshi/src/query/aggregate' && bash <(curl -s https://codecov.io/bash) -s target/kcov; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo coveralls --exclude-pattern '/toshi/src/bin,/src/bin,/bin,/target,/toshi/src/query/aggregate'; fi
