[package]
name    = "toshi"
version = "0.1.1"
authors = ["Stephen Carman <shcarman@gmail.com>"]
description = "A full text search engine based on Tantivy"
repository = "https://github.com/toshi-search/Toshi"
license = "MIT"
build = "build.rs"

[[bin]]
name = "toshi"
path = "src/bin/main.rs"

[lib]
path = "src/lib.rs"

[build-dependencies]
capnpc = "^0.9"

[dependencies]
gotham            = { git = "https://github.com/gotham-rs/gotham", rev = "7ec494e" }
gotham_derive     = { git = "https://github.com/gotham-rs/gotham", rev = "7ec494e" }
hyper             = "^0.12"
mime              = "^0.3"
serde             = "^1.0"
serde_derive      = "^1.0"
serde_json        = "^1.0"
futures           = "^0.1"
tantivy           = "^0.7"
tokio             = "^0.1"
config            = "^0.9"
log               = "^0.4"
pretty_env_logger = "^0.2"
failure           = "^0.1"
crossbeam-channel = "^0.2"
capnp             = "^0.9"
clap              = "^2.32"
uuid              = { version = "0.7", features = ["v4"] }

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
lto = true
rpath = false
codegen-units = 1
