[package]
name    = "toshi"
version = "0.1.1"
authors = ["Stephen Carman <shcarman@gmail.com>"]
description = "A full text search engine based on Tantivy"
repository = "https://github.com/toshi-search/Toshi"
license = "MIT"
edition = "2018"

[[bin]]
name = "toshi"

[lib]
path = "src/lib.rs"

[workspace]
members = [ "./", "toshi-proto" ]

[dependencies]
toshi-proto            = { path = "toshi-proto" }
tower-buffer           = { git = "https://github.com/tower-rs/tower" }
tower-grpc             = { git = "https://github.com/tower-rs/tower-grpc" }
tower-h2               = { git = "https://github.com/tower-rs/tower-h2" }
tower                  = { git = "https://github.com/tower-rs/tower" }
tower-service          = { git = "https://github.com/tower-rs/tower" }
tower-http             = { git = "https://github.com/tower-rs/tower-http" }
tower-request-modifier = { git = "https://github.com/tower-rs/tower-http" }
tower-consul           = { git = "https://github.com/LucioFranco/tower-consul" }
futures-watch          = { git = "https://github.com/carllerche/better-future" }
tokio-connect          = { git = "https://github.com/carllerche/tokio-connect" }
tower-web              = "^0.3"
http                   = "^0.1"
h2                     = "^0.1"
flate2                 = "^1.0"
bytes                  = "^0.4"
prost                  = "^0.5"
prost-derive           = "^0.5"
hyper                  = "^0.12"
hyper-tls              = "^0.3"
serde_json             = "^1.0"
futures                = "^0.1"
tantivy                = "^0.9"
tokio                  = "^0.1"
tokio-executor         = "^0.1"
tokio-signal           = "^0.2"
config                 = "^0.9"
log                    = "^0.4"
pretty_env_logger      = "^0.3"
failure                = "^0.1"
num_cpus               = "^1.10"
hostname               = "^0.1"
base64                 = "^0.10"
crossbeam              = "^0.7"
hashbrown              = "^0.3"
rand                   = { version = "^0.6", features = ["log"] }
serde                  = { version = "^1.0", features = ["derive"] }
clap                   = { version = "^2.32", features = ["color"] }
uuid                   = { version = "^0.7", features = ["v4"] }
systemstat             = { git = "https://github.com/toshi-search/systemstat" }

[dev-dependencies]
remove_dir_all = "0.5.1"
pretty_assertions = "0.6.1"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
lto = true
rpath = false
codegen-units = 1

[patch.crates-io]
tower-service = { git = "https://github.com/tower-rs/tower" }
