[package]
name    = "toshi"
version = "0.1.1"
authors = ["Stephen Carman <shcarman@gmail.com>"]
description = "A full text search engine based on Tantivy"
repository = "https://github.com/toshi-search/Toshi"
license = "MIT"
edition = "2018"

[[bin]]
name = "toshi"

[[bin]]
name = "toshi-placement"

[lib]
path = "src/lib.rs"

[build-dependencies]
tower-grpc-build = { git = "https://github.com/tower-rs/tower-grpc" }

[dependencies]
tower-web         = "0.3.3"
http              = "0.1.14"
tower-grpc        = { git = "https://github.com/tower-rs/tower-grpc" }
tower-h2          = { git = "https://github.com/tower-rs/tower-h2" }
tower-util        = { git = "https://github.com/tower-rs/tower" }
tower-http        = { git = "https://github.com/tower-rs/tower-http" }
tokio-connect     = { git = "https://github.com/carllerche/tokio-connect" }
flate2            = "^1.0"
bytes             = "^0.4"
prost             = "^0.4"
prost-derive      = "^0.4"
hyper             = "^0.12"
hyper-tls         = "^0.3"
mime              = "^0.3"
serde             = "^1.0"
serde_derive      = "^1.0"
serde_json        = "^1.0"
futures           = "^0.1"
tantivy           = "^0.7"
tokio             = "^0.1"
tokio-signal      = "^0.2"
tokio-tls         = "^0.2"
config            = "^0.9"
log               = "^0.4"
pretty_env_logger = "^0.3"
failure           = "^0.1"
crossbeam         = "^0.6"
clap              = { version = "^2.32", features = ["color"] }
num_cpus          = "^1.0"
systemstat        = { git = "https://github.com/toshi-search/systemstat", branch = "master" }
uuid              = { version = "0.7", features = ["v4"] }

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
lto = true
rpath = false
codegen-units = 1