[package]
name    = "toshi"
version = "0.1.0"
authors = ["Stephen Carman <shcarman@gmail.com>"]
build = "build.rs"

[[bin]]
name = "toshi"
path = "src/bin/main.rs"

[lib]
path = "src/lib.rs"

[build-dependencies]
capnpc = "0.9.0"

[dependencies]
gotham            = "0.2"
gotham_derive     = "0.2"
hyper             = "0.12"
mime              = "0.3"
serde             = "1.0"
serde_derive      = "1.0"
serde_json        = "1.0"
lazy_static       = "1.1"
futures           = "0.1"
tantivy           = "0.7"
tokio             = "0.1"
config            = "0.9.0"
log               = "0.4"
pretty_env_logger = "0.2"
failure           = "0.1.2"
crossbeam-channel = "0.2"
capnp             = "0.9"


[profile.release]
opt-level = 3
debug = false
debug-assertions = false
lto = true
rpath = false
codegen-units = 1