[package]
name    = "toshi"
version = "0.1.1"
authors = ["Stephen Carman <shcarman@gmail.com>"]
description = "A full text search engine based on Tantivy"
repository = "https://github.com/toshi-search/Toshi"
license = "MIT"

[[bin]]
name = "toshi"
path = "src/bin/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
gotham            = { git = "https://github.com/gotham-rs/gotham", rev = "9e60d8752fd5bb569f4156e60ee1919198702273"}
gotham_derive     = { git = "https://github.com/gotham-rs/gotham", rev = "9e60d8752fd5bb569f4156e60ee1919198702273"}
tower-web         = "0.3.3"
hyper             = "^0.12"
mime              = "^0.3"
serde             = "^1.0"
serde_derive      = "^1.0"
serde_json        = "^1.0"
futures           = "^0.1"
tantivy           = "^0.7"
tokio             = "^0.1"
tokio-signal      = "^0.2"
config            = "^0.9"
log               = "^0.4"
pretty_env_logger = "^0.2"
failure           = "^0.1"
crossbeam         = "^0.5"
clap              = "^2.32"
num_cpus          = "^1.0"
systemstat        = { git = "https://github.com/toshi-search/systemstat", branch = "master" }
uuid              = { version = "0.7", features = ["v4"] }

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
lto = true
rpath = false
codegen-units = 1