[package]
name    = "toshi"
version = "0.1.1"
authors = ["Stephen Carman <shcarman@gmail.com>"]
description = "A full text search engine based on Tantivy"
repository = "https://github.com/toshi-search/Toshi"
license = "MIT"
edition = "2018"
build = "build.rs"

[[bin]]
name = "toshi"

[lib]
path = "src/lib.rs"

[build-dependencies]
tower-grpc-build = { git = "https://github.com/tower-rs/tower-grpc" }

[dependencies]
tower-service        = { git = "https://github.com/tower-rs/tower" }
tower-direct-service = { git = "https://github.com/tower-rs/tower" }
tower-discover       = { git = "https://github.com/tower-rs/tower" }
tower-buffer         = { git = "https://github.com/tower-rs/tower" }
tower-grpc           = { git = "https://github.com/tower-rs/tower-grpc" }
tower-h2             = { git = "https://github.com/tower-rs/tower-h2" }
tower-util           = { git = "https://github.com/tower-rs/tower" }
tower-http           = { git = "https://github.com/tower-rs/tower-http" }
tower-consul         = { git = "https://github.com/LucioFranco/tower-consul" }
tokio-connect        = { git = "https://github.com/carllerche/tokio-connect" }
tower-web            = "^0.3"
http                 = "^0.1"
h2                   = "0.1.16"
taken                = "0.1.1"
flate2               = "^1.0"
futures-watch        = { git = "https://github.com/carllerche/better-future" }
chashmap             = "^2.2"
bytes                = "^0.4"
prost                = "^0.4"
prost-derive         = "^0.4"
hyper                = "^0.12"
hyper-tls            = "^0.3"
mime                 = "^0.3"
serde_json           = "^1.0"
futures              = "^0.1"
tantivy              = "^0.8"
tokio                = "^0.1"
tokio-executor       = "^0.1"
tokio-threadpool     = "^0.1"
tokio-signal         = "^0.2"
tokio-tls            = "^0.2"
config               = "^0.9"
log                  = "^0.4"
pretty_env_logger    = "^0.3"
failure              = "^0.1"
crossbeam            = "^0.7"
num_cpus             = "^1.10"
serde                = { version = "^1.0", features = ["derive"] }
clap                 = { version = "^2.32", features = ["color"] }
uuid                 = { version = "^0.7", features = ["v4"] }
systemstat           = { git = "https://github.com/toshi-search/systemstat" }

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
lto = true
rpath = false
codegen-units = 1

#[patch.crates-io]
#tower-service        = { git = "https://github.com/tower-rs/tower" }
#tower-direct-service = { git = "https://github.com/tower-rs/tower" }
#tower-buffer         = { git = "https://github.com/tower-rs/tower" }
#tower-grpc           = { git = "https://github.com/tower-rs/tower-grpc" }
#tower-h2             = { git = "https://github.com/tower-rs/tower-h2" }
#tower-util           = { git = "https://github.com/tower-rs/tower" }
#tower-http           = { git = "https://github.com/tower-rs/tower-http" }
#tower-consul         = { git = "https://github.com/LucioFranco/tower-consul" }
#tokio-connect        = { git = "https://github.com/carllerche/tokio-connect" }
