[package]
name    = "toshi-proto"
version = "0.1.0"
authors = ["Stephen Carman <shcarman@gmail.com>"]
description = "A full text search engine based on Tantivy"
repository = "https://github.com/toshi-search/Toshi"
license = "MIT"
edition = "2018"
build = "build.rs"

[build-dependencies]
tonic-build = { git = "https://github.com/hyperium/tonic" }

[dependencies]
tonic        = { git = "https://github.com/hyperium/tonic" }
bytes        = "^0.4"
prost        = "^0.5"
prost-types  = "^0.6"
prost-derive = "^0.5"
